[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dnois"
version = "0.1.1-dev.20251118"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "torch>=2.5",
]
authors = [
    { name = "Jiaqi Guo", email = "gjq@tongji.edu.cn" }
]
description = "Differentiable Numerical Optical Imaging Simulation"
readme = "README.md"
license = "MIT"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"dnois.base" = ["fl.csv"]